Add tests for OrderPayable
api3dao/airnode-protocol-v1 pull request #130
Opened 2023-04-21 09:09 UTC by alikonuk1

Added tests that covers various cases and validates the expected behavior for functions in OrderPayable.sol, which will be added on this pr #128

2023-04-26 07:22 UTC, bbenligiray requested changes
I ran `test:coverage` and saw that OrderPayable is not 100% covered. Anything less than 100% is not acceptable for contracts, and even 100% coverage by itself does not guarantee good tests.

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +      context('Order Id not zero', function () {
As a personal stylistic choice, I use regular English in `context()` strings. I'd prefer `Order signer is valid` (we don't need to shorten this as this is not a revert string) and `Order Id not zero` (this is not code, we don't need to use camel case).

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +            context('Order didnt paid before', function () {
Missing apostrophe, broken grammar. Contract code is formal writing so you shouldn't use contractions anyway (so `did not` over `didn't`).

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +              context('Signiture match', function () {
Typo

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +    context('Order signer valid', function () {
Context is `Order signer valid` but there is no alternative context, so this is redundant

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +  describe('payForOrder', function () {
The conditions should be tested in the order that they are validated. For example, for `payForOrder()`
- Order ID needs to be non-zero
- Order needs to not have expired
- Signer needs to be the manager or an order signer (these need to be tested separately)
- Payment amount needs to be non-zero
- Order needs to not have been paid for
- Signature has to match

Your contexts should follow the same order to make sure that you're not missing any branches

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +                  );
Duplicated too many times, extract this as a function

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +                  const chainId = network.chainId;
Can be a single line since `network` isn't used again

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +          const orderId = ethers.utils.hexZeroPad(
https://docs.ethers.org/v5/api/utils/constants/#constants-HashZero

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +    context('Caller is manager or withdrawer', function () {
Test separately

2023-04-26 07:22 UTC, bbenligiray commented on test/utils/OrderPayable.sol.js
> +  describe('withdraw', function () {
You should test the case where the value transfer reverts. You can do that by setting the `recipient` to be a contract that doesn't have a `receive()` function (for example AccessControlRegistry).

2023-04-26 21:57 UTC, alikonuk1 commented
> I ran `test:coverage` and saw that OrderPayable is not 100% covered. Anything less than 100% is not acceptable for contracts, and even 100% coverage by itself does not guarantee good tests.

I have updated the tests for OrderPayable contract, now it have 100% coverage. I would love to know if there is still an area for improvement.

2023-05-25 09:03 UTC, bbenligiray approved these changes
I applied some changes [here](https://github.com/api3dao/airnode-protocol-v1/pull/134)

2023-05-25 09:03 UTC, merged